server:
  port: 80
#  servlet:
#    context-path: /demo/

# DataSource Config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dishmanagedatabase
    username: root
    password: root
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
    timeout: 30m
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 30s

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

wxapp:
  appid: wx7b1f274e59dc61e8
  secret: c207677a41225e91dfeafdfbdeac0ebc
  grantType: authorization_code

